version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db-data:/data/db
  redis:
    image: redis
    restart: unless-stopped

volumes:
  db-data:
